#!/usr/bin/env python3
"""
Install pre-commit and pre-push hooks into a git repository.
"""
import os
import sys


def install_hooks(repo_path='.'):
    repo_path = os.path.abspath(repo_path)
    git_dir = os.path.join(repo_path, '.git')

    if not os.path.isdir(git_dir):
        print(f"❌ Error: {repo_path} is not a git repository")
        sys.exit(1)

    hooks_dir = os.path.join(git_dir, 'hooks')
    os.makedirs(hooks_dir, exist_ok=True)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    hook_runner = os.path.join(script_dir, 'hook_runner.py')

    if not os.path.exists(hook_runner):
        print(f"❌ Error: hook_runner.py not found at {hook_runner}")
        sys.exit(1)

    # Create pre-commit hook
    pre_commit = os.path.join(hooks_dir, 'pre-commit')
    with open(pre_commit, 'w', newline='\n') as f:
        f.write(f'#!/bin/sh\n')
        f.write(f'# Auto-generated by pre-commit-check\n')
        f.write(f'python3 "{hook_runner}" --hook-type pre-commit "{repo_path}"\n')
    os.chmod(pre_commit, 0o755)
    print(f"✅ Installed: {pre_commit}")

    # Create pre-push hook
    pre_push = os.path.join(hooks_dir, 'pre-push')
    with open(pre_push, 'w', newline='\n') as f:
        f.write(f'#!/bin/sh\n')
        f.write(f'# Auto-generated by pre-commit-check\n')
        f.write(f'python3 "{hook_runner}" --hook-type pre-push "{repo_path}"\n')
    os.chmod(pre_push, 0o755)
    print(f"✅ Installed: {pre_push}")

    print(f"\n🔒 Hooks are active in: {repo_path}")
    print("   • git commit  → 触发代码测试 + 安全扫描 + 提交信息生成")
    print("   • git push    → 触发代码测试 + 安全扫描")
    print("\n💡 To bypass hooks in emergency: git commit --no-verify / git push --no-verify")


if __name__ == '__main__':
    repo_path = sys.argv[1] if len(sys.argv) > 1 else '.'
    install_hooks(repo_path)
